Beginning to add an amd64 VM (to address #17)

diff --git a/autobuild-setup b/autobuild-setup
--- a/autobuild-setup
+++ b/autobuild-setup
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 storagedir="$HOME/.local/share/autobuild"
 
@@ -79,10 +79,10 @@ echo "--"
 echo "This script can also set up a virtual-machine Build Farm"
 echo "This can be used to build packages on other architectures or for other distributions"
 echo "Currently the build farm contains the following VMs:"
+echo "  - Debian Stable amd64"
 echo "  - Debian Stable i386"
 echo "  - Debian Stable arm64"
-echo "Setting the i386 VM up generally takes about 20-30 minutes"
-echo "However, ARM VMs can take much longer (~2 hours each)"
+echo "Setting up the VMs can take a while."
 echo "--"
 
 buildingvms=0
@@ -99,8 +99,18 @@ done
 if [[ buildingvms -eq 1 ]]; then	
 	cd "$storagedir/build-farm" || (echo "Could not enter $storagedir/build-farm. Run this script through 'autobuild -s'"; exit)
 
+	building_amd64vm=0
 	building_i386vm=0
 	building_arm64vm=0
+
+	while true; do
+		read -p "BUILD FARM: Do you want to build packages for amd64? (y/n) " yn
+		case $yn in
+			[Yy]* ) building_amd64vm=1; break;;
+			[Nn]* ) break;;
+			* ) echo "Answer yes or no";;
+		esac
+	done
 
 	while true; do
 		read -p "BUILD FARM: Do you want to build packages for i386? (y/n) " yn
@@ -120,10 +130,28 @@ if [[ buildingvms -eq 1 ]]; then
 		esac
 	done
 
+	if [[ $building_amd64vm -eq 1 ]]; then
+		echo "  Creating amd64 VM..."
+		
+		cd debian-stable-amd64 || (echo "$storagedir is not properly configured. Run this script through 'autobuild -s'"; exit)
+
+		cp ../preseed.cfg ./preseed.cfg
+		
+		make download
+		make image
+		make boot-install
+		make clean
+		
+		echo "  Created amd64 VM."
+		cd ..
+	fi
+
 	if [[ $building_i386vm -eq 1 ]]; then
 		echo "  Creating i386 VM..."
 		
 		cd debian-stable-i386 || (echo "$storagedir is not properly configured. Run this script through 'autobuild -s'"; exit)
+
+		cp ../preseed.cfg ./preseed.cfg
 		
 		make download
 		make image
@@ -138,6 +166,8 @@ if [[ buildingvms -eq 1 ]]; then
 		echo "  Creating arm64 VM..."
 		
 		cd debian-stable-arm64 || (echo "$storagedir is not properly configured. Run this script through 'autobuild -s'"; exit)
+
+		cp ../preseed.cfg ./preseed.cfg
 		
 		make download
 		make image
