Autobuild now creates a new Debian repo for the user Rather than relying on the user already owning one, we just go ahead and create one (incl. signing key, etc) This repo can be shipped either as a GitHub Pages site, or via some web server on the host machine, etc. We just create the files This closes #35 and #27

diff --git a/autobuild-setup b/autobuild-setup
--- a/autobuild-setup
+++ b/autobuild-setup
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# autobuild
+# autobuild setup
 # Copyright (C) 2024 rail5
 # Free software (GNU Affero GPL v3)
 
@@ -11,6 +11,7 @@ fi
 
 local_storage_directory="/var/autobuild"
 autobuild_directory="/usr/share/autobuild"
+CONFIG_FILE="$local_storage_directory/config.toml"
 window_title="Autobuild setup"
 
 # Copy any updated files to $local_storage_directory/build-farm in case an upgrade took place
@@ -93,6 +94,207 @@ function setup_build_farm() {
 
 }
 
+function create_new_debian_repository() {
+	# Ask the user for the name and email to use for the package signing key
+	local user_email="" user_name="" signing_key_fingerprint="" repo_url="" repo_friendlyname="" default_index_html_code="" repo_will_be_ghpages=false
+	{ user_email="$(dialog --title "$window_title" \
+		--inputbox "Input the EMAIL to be associated with the package GPG signing key" 15 55 \
+		2>&1 1>&3 3>&- )"; } 3>&1
+	
+	echo ""
+	echo ""
+	echo "$user_email"
+
+	# Check if we've already made a key with that email
+	if gpg --list-secret-keys "$user_email"; then
+		key_exists_already=true
+	else
+		key_exists_already=false
+	fi
+	use_old_key=$key_exists_already
+
+	if [[ $key_exists_already == true ]]; then
+		dialog --title "$window_title" \
+			--yesno "A signing key already exists under '$user_email'.\n\nWould you like to DELETE this one and create a new signing key?" 15 55
+		
+		case $? in
+			0)
+				use_old_key=false
+				;;
+			1)
+				use_old_key=true
+				user_name=$(gpg --with-colons -k "$user_email" | awk -F: '$1=="uid" {print $10}' | sed 's/<.\+>//')
+				;;
+		esac
+	fi
+	
+	if [[ $use_old_key == false ]]; then
+		{ user_name="$(dialog --title "$window_title" \
+			--inputbox "Input the NAME to be associated with the package GPG signing key" 15 55 \
+			2>&1 1>&3 3>&- )"; } 3>&1
+		
+		if [[ $key_exists_already == true ]]; then
+			# Delete the old key before creating the new key
+			old_fingerprint=$(gpg -K --with-colons "$user_email" | awk -F: '$1=="fpr" {print $10}' | head -n 1)
+			gpg --batch --yes --delete-secret-keys "$old_fingerprint"
+			gpg --batch --yes --delete-keys "$user_email"
+		fi
+
+		# Create the new key
+		gpg --batch --gen-key <<EOF
+%no-protection
+Key-Type:1
+Key-Length:4096
+Subkey-Type:1
+Subkey-Length:4096
+Name-Real: $user_name
+Name-Email: $user_email
+Expire-Date:0
+EOF
+
+	fi
+
+	# Get the signing key's fingerprint!
+	signing_key_fingerprint=$(gpg -K --with-colons "$user_email" | awk -F: '$1=="fpr" {print $10}' | head -n 1)
+
+	# Delete any old repository which may or may not exist
+	rm -rf "${local_storage_directory:?}/repo/"
+
+	# Prepare the new repository for reprepro
+	mkdir -p "${local_storage_directory:?}/repo/conf"
+	cat > "${local_storage_directory:?}/repo/conf/distributions" <<EOF
+Origin: $user_name
+Label: $user_name
+Codename: unstable
+Architectures: source amd64 i386 arm64
+Components: main
+Description: Apt repository for $user_name
+SignWith: $signing_key_fingerprint
+EOF
+
+	# Ask the user for the repo URL
+	{ repo_url="$(dialog --title "$window_title" \
+			--inputbox "Input the FULL URL of the Debian Repository\nFor example: https://my.site.com/path/to/repo" 15 55 \
+			2>&1 1>&3 3>&- )"; } 3>&1
+
+	# Get the repo "friendly name":
+	## Remove non-alphanumeric characters from the user's name
+	## And convert the remainder to lowercase
+	# shellcheck disable=SC2001
+	repo_friendlyname=$(sed 's/[^A-Za-z0-9\-]//g' <<<"$user_name" | tr '[:upper:]' '[:lower:]')
+
+	# Export the public key to a file
+	gpg --export "$signing_key_fingerprint" > "${local_storage_directory:?}/repo/${repo_friendlyname:?}-signing-key.gpg"
+
+	# Create the repo .list file
+	cat > "${local_storage_directory:?}/repo/${repo_friendlyname:?}.list" <<EOF
+deb $repo_url unstable main
+deb-src $repo_url unstable main
+EOF
+
+	# Create the default index.html file for the repo
+	default_index_html_code=$(cat "${autobuild_directory:?}/repository/default-index.html")
+	default_index_html_code="${default_index_html_code//\%REPO_FRIENDLYNAME\%/"$repo_friendlyname"}"
+	default_index_html_code="${default_index_html_code//\%REPO_URL\%/"$repo_url"}"
+
+	cat > "${local_storage_directory:?}/repo/index.html" <<<"$default_index_html_code"
+	cp "${autobuild_directory:?}/repository/run_prettify.js" "${local_storage_directory:?}/repo/run_prettify.js"
+
+	# Will this be some web server, or GitHub Pages?
+	# If it's GitHub Pages, we'll have to push changes etc rather than just change files
+	dialog --title "$window_title" \
+		--yesno "Will this repository be served via GitHub Pages?" 15 55
+	
+	case $? in
+		0)
+			repo_will_be_ghpages=true
+			;;
+		1)
+			repo_will_be_ghpages=false
+			;;
+	esac
+
+	local repo_conf_file="${local_storage_directory:?}/repo/autobuild_repo.conf"
+
+	echo "[repo]" > "${repo_conf_file:?}"
+
+	if [[ $repo_will_be_ghpages == true ]]; then
+		# Parse autobuild config.toml to get GitHub Credentials
+		local config_json=""
+		config_json=$(toml2json "$CONFIG_FILE")
+		GITHUB_OWNER=$(jq -r ".github.repo_owner" <<<"$config_json")
+		GITHUB_EMAIL=$(jq -r ".github.email" <<<"$config_json")
+		GITHUB_ACCESS_TOKEN=$(jq -r ".github.access_token" <<<"$config_json")
+
+		if [[ "$GITHUB_OWNER" == "" || "$GITHUB_EMAIL" == "" || "$GITHUB_ACCESS_TOKEN" == "" ]]; then
+			echo "ghpages = false" >> "${repo_conf_file:?}"
+			dialog --title "$window_title" \
+				--infobox "Error: Your GitHub credentials are not properly configured in /var/autobuild/config.toml\n\nBefore trying again, please ensure that that file contains:\n - Your GitHub username\n - Your GitHub email\n - Your GitHub Access Token" 15 55; sleep 7
+			return
+		fi
+
+		echo "ghpages = true" >> "${repo_conf_file:?}"
+
+		# Ask the user for the Github URL
+		{ ghpages_url="$(dialog --title "$window_title" \
+				--inputbox "Input the FULL URL of the GitHub Repository that will be used\nFor example: https://github.com/user/repository.git" 15 55 \
+				2>&1 1>&3 3>&- )"; } 3>&1
+
+		echo "ghpages_url = \"$ghpages_url\"" >> "${repo_conf_file:?}"
+
+		# Initialize the git repo, set origin, and push
+		cd "${local_storage_directory:?}/repo" || (echo ""; echo "Confusing and fatal error in setting up GitHub Pages repository"; exit)
+
+		# Add our necessary credentials to the URL to push (https://user:pass@github.com/etc)
+		local push_url="${ghpages_url/:\/\//:\/\/$GITHUB_OWNER:$GITHUB_ACCESS_TOKEN@}"
+
+		local temporary_repo_changes_directory=""
+		temporary_repo_changes_directory=$(mktemp --tmpdir -d)
+		mv -f "./"* "${temporary_repo_changes_directory:?}/"
+
+		git init
+		git config user.email "$GITHUB_EMAIL"
+		git config user.name "$GITHUB_OWNER"
+		git remote add origin "$ghpages_url"
+		git pull "$push_url" -q
+
+		mv -f "${temporary_repo_changes_directory:?}/"* "./"
+		rm -rf "${temporary_repo_changes_directory:?}"
+
+		git add --all
+		git commit -m "Initialized Autobuild GitHub Pages Debian Repository"
+		git branch -M main
+		
+		git push "$push_url" --all # Push changes
+	else
+		echo "ghpages = false" >> "${repo_conf_file:?}"
+	fi
+
+	dialog --title "$window_title" \
+		--infobox "Your Debian Repo is now configured\n\nYou can check the welcome page at $repo_url\nIf your repo is managed via GitHub Pages, it may take a few moments to publish." 15 55; sleep 7
+}
+
+function setup_debian_repo() {
+	# First, check: do we have one already?
+	debian_repository_already_exists=$(test -f /var/autobuild/repo/autobuild_repo.conf && echo "true" || echo "false")
+
+	if [[ $debian_repository_already_exists == true ]]; then
+		dialog --title "$window_title" \
+			--yesno "It looks like a repository already exists in /var/autobuild/repo.\nWould you like to DELETE this repository and create a new one?" 15 55
+
+			case $? in
+				0)
+					create_new_debian_repository
+					return ;;
+				1)
+					return ;;
+			esac
+	else
+		create_new_debian_repository
+		return
+	fi
+}
+
 function clear_builds_directory() {
 	rm -rf "${local_storage_directory:?}/builds/"*
 	dialog --title "$window_title" \
@@ -102,21 +304,26 @@ function clear_builds_directory() {
 function setup_main_menu() {
 	{ next_page="$(dialog --title "$window_title" \
 		--menu "This menu can be reached anytime with 'autobuild -s'" 15 55 \
-		3 \
+		4 \
 		1 "Install build farm" \
-		2 "Clear 'builds' directory" \
-		3 "Exit" \
+		2 "Configure Debian Repository" \
+		3 "Clear 'builds' directory" \
+		4 "Exit" \
 		2>&1 1>&3 3>&- )"; } 3>&1 # Capture stderr output into next_page variable
 					# 'dialog' writes user responses to stderr
 
 	case $next_page in
-		"" | 3) # User pressed "cancel" or "Exit"
+		"" | 4) # User pressed "cancel" or "Exit"
 			exit ;;
 		1)
 			setup_build_farm
 			setup_main_menu
 			;;
 		2)
+			setup_debian_repo
+			setup_main_menu
+			;;
+		3)
 			clear_builds_directory
 			setup_main_menu
 			;;
diff --git a/autobuildd b/autobuildd
--- a/autobuildd
+++ b/autobuildd
@@ -25,6 +25,8 @@ pkgs_build_base_directory="builds/$(date +%Y-%h-%d-%H%M%S)"
 
 CONFIG_FILE="$local_storage_directory/config.toml"
 
+REPO_CONFIG_FILE="$local_storage_directory/repo/autobuild_repo.conf"
+
 BUILDFARM_SCRIPTS_FILE="$autobuild_directory/build-farm/scripts/scripts.sh"
 
 if [ ! -d "$local_storage_directory" ]; then
@@ -548,29 +550,29 @@ function push_forgejo_release_page() {
 }
 
 function prepare_git_debian_repo() {
-	# Clone the git repo into a local directory
-	cd "$local_storage_directory" || { echo "Could not cd into \"$local_storage_directory\""; echo "Have you configured your Debian repo properly in the CONFIG file?"; echo "Try editing your CONFIG file with 'autobuild -c'"; graceful_exit 1; }
-	git clone "$git_debianrepo" "repo" -q 2>/dev/null
+	if [[ $REPO_IS_GHPAGES == "true" ]]; then
+		cd "$local_storage_directory/repo" || { echo "Could not cd into \"$local_storage_directory\""; echo "Have you configured your Debian repo properly in the CONFIG file?"; graceful_exit 1; }
 
-	cd "repo" || { echo "Could not cd into \"$local_storage_directory/repo\""; echo "Have you configured your Debian repo properly in the CONFIG file?"; echo "Try editing your CONFIG file with 'autobuild -c'"; graceful_exit 1; }
+		git config user.email "$GITHUB_EMAIL"
+		git config user.name "$GITHUB_OWNER"
 
-	git config user.email "$GITHUB_EMAIL"
-        git config user.name "$GITHUB_OWNER"
-
-	git reset --hard
-	git pull -q
+		git reset --hard
+		git pull -q
+	fi
 }
 
 function close_git_debian_repo() {
-	cd "$local_storage_directory/repo" || { echo "Could not cd into \"$local_storage_directory/repo\""; echo "Have you configured your Debian repo properly in the CONFIG file?"; echo "Try editing your CONFIG file with 'autobuild -c'"; graceful_exit 1; }
+	if [[ $REPO_IS_GHPAGES == "true" ]]; then
+		cd "$local_storage_directory/repo" || { echo "Could not cd into \"$local_storage_directory/repo\""; echo "Have you configured your Debian repo properly in the CONFIG file?"; graceful_exit 1; }
 
-	# Add our necessary credentials to the URL to push (https://user:pass@github.com/etc)
-        local push_url="${git_debianrepo/:\/\//:\/\/$GITHUB_OWNER:$GITHUB_ACCESS_TOKEN@}"
-	
-	# Push any changes that we made before we called this function
-	git add --all
-	git commit -m "Updated packages"
-	git push "$push_url" --all -q
+		# Add our necessary credentials to the URL to push (https://user:pass@github.com/etc)
+		local push_url="${REPO_GHPAGES_URL/:\/\//:\/\/$GITHUB_OWNER:$GITHUB_ACCESS_TOKEN@}"
+		
+		# Push any changes that we made before we called this function
+		git add --all
+		git commit -m "Updated packages"
+		git push "$push_url" --all -q
+	fi
 }
 
 function push_to_debian_repo() {
@@ -594,7 +596,7 @@ function push_to_debian_repo() {
 	
 	# Add .changes files to the repo
 	for changes_file in "$base_release_directory/$PKGNAME/"*.changes; do
-		reprepro -P optional include "$debian_distribution" "$changes_file"
+		reprepro --ignore=wrongdistribution -P optional include "$debian_distribution" "$changes_file"
 	done
 }
 
@@ -779,6 +781,7 @@ building_locally=false
 building_on_amd64=false
 building_on_i386=false
 building_on_arm64=false
+debian_repo_is_configured=false
 distribute_to_debian_repo=false
 
 while true; do
@@ -815,7 +818,15 @@ while true; do
 			# Handled by the autobuild client
 			shift ;;
 		-d | --debian-repo )
-			distribute_to_debian_repo=true; shift ;;
+			if [[ -f "$REPO_CONFIG_FILE" ]]; then
+				debian_repo_is_configured=true
+			fi
+			if [[ $debian_repo_is_configured == "true" ]]; then
+				distribute_to_debian_repo=true
+			else
+				echo "Debian Repository is not configured"
+			fi
+			shift ;;
 		-f | --forgejo-page )
 			make_forgejo_release_pages=true; shift ;;
 		-g | --github-page )
@@ -881,8 +892,6 @@ GITHUB_EMAIL=$(jq -r ".github.email" <<<"$config_json")
 ### Check for Github access token
 GITHUB_ACCESS_TOKEN=$(jq -r ".github.access_token" <<<"$config_json")
 
-git_debianrepo=$(jq -r ".github.git_debian_repo" <<<"$config_json")
-
 ### Forgejo
 FORGEJO_INSTANCE_URL=$(jq -r ".forgejo.instance_url" <<<"$config_json")
 
@@ -890,6 +899,16 @@ FORGEJO_OWNER=$(jq -r ".forgejo.repo_owner" <<<"$config_json")
 
 ### Check for Forgejo access token
 FORGEJO_ACCESS_TOKEN=$(jq -r ".forgejo.access_token" <<<"$config_json")
+
+
+# If the Debian Repo has been configured, parse that config file
+if [[ $debian_repo_is_configured == "true" ]]; then
+	repo_config_json=$(toml2json "$REPO_CONFIG_FILE")
+
+	REPO_IS_GHPAGES=$(jq -r ".repo.ghpages" <<<"$repo_config_json")
+
+	REPO_GHPAGES_URL=$(jq -r ".repo.ghpages_url" <<<"$repo_config_json")
+fi
 
 ##################################################
 
