Script cleanup

diff --git a/autobuild b/autobuild
--- a/autobuild
+++ b/autobuild
@@ -9,7 +9,7 @@ if [ "$(whoami)" == "root" ]; then
 	sleep 1
 fi
 
-tempdirectory=$(dirname $(mktemp -u))
+tempdirectory=$(dirname "$(mktemp -u)")
 initdir=$(mktemp --tmpdir -d autobuild.XXXXXXXXXXXX)
 storagedir="$HOME/.local/share/autobuild"
 buildfarmdir="$storagedir/build-farm"
@@ -61,7 +61,9 @@ fi
 
 mkdir -p "$packagedir"
 
+# shellcheck source=./config.example
 . "$CONFIG_FILE"
+# shellcheck source=./build-farm/scripts/scripts.sh
 . "$BUILDFARM_SCRIPTS_FILE"
 
 
@@ -74,13 +76,14 @@ mkdir -p "$packagedir"
 OLDIFS="$IFS"
 IFS="
 "
-for subdir in $(ls "$packagedir"); do
+for subdir in "$packagedir/"*; do
+	subdir="$(basename "$subdir")"
 	if [[ "${packages[$subdir]+true}" ]]; then
 		# Package exists in our packages array
 		continue
 	else
 		# Package DOES NOT exist in our packages array
-		rm -rf "$packagedir/$subdir"
+		rm -rf "${packagedir:?}/${subdir:?}"
 	fi
 done
 IFS="$OLDIFS"
@@ -106,7 +109,7 @@ function build_package_universal() {
 		echo "bag args to build_package_universal" && exit 1
 	fi
 	
-	local PKGNAME="$1" GITURL="$2" BASEBUILD="$3" I386BUILD="$4" ARM64BUILD="$5" CLONESOURCES=0
+	local PKGNAME="$1" GITURL="$2" BASEBUILD="$3" I386BUILD="$4" ARM64BUILD="$5"
 	
 	# Variables:
 	## PKGNAME, GITURL: Self-explanatory
@@ -130,19 +133,19 @@ function build_package_universal() {
 	mkdir -p "$releasedir"
 	
 	# Pull updates to the source code from GITURL into our local package directory
-	cd "$packagedir"
+	cd "$packagedir" || { echo "Could not cd into \"$packagedir\""; exit 1; }
 	git clone "$GITURL" "$PKGNAME" -q 2>/dev/null # Clone in case we don't already have it
-	cd "$PKGNAME"
+	cd "$PKGNAME" || { echo "Could not cd into \"$PKGNAME\""; exit 1; }
 	git reset --hard
 	git pull -q # Pull changes in case we do already have it (an older version)
 
 	# Copy the updated source code into a temp directory named PKGNAME
-	cd "$initdir/$pkgs_build_base_directory/srconly"
+	cd "$initdir/$pkgs_build_base_directory/srconly" || { echo "Could not cd into package source directory"; exit 1; }
 	mkdir "$PKGNAME"
 	cp -r "$packagedir/$PKGNAME/"* "./$PKGNAME/"
 	
 	# Tar it up so we can pass it to the build farm VMs later
-	cd "$srcdir"
+	cd "$srcdir" || { echo "Could not cd into \"$srcdir\""; exit 1; }
 	tar -czf "$sourcetarball" .
 
 
@@ -175,7 +178,7 @@ function build_package_universal() {
 		cp -r "$srcdir/"* "$builddir/"
 		
 		# Move to the build directory, don't mess with the source directory
-		cd "$builddir"
+		cd "$builddir" || { echo "Could not cd into \"$builddir\""; exit 1; }
 		
 		# Build package
 		debuild -us -uc
@@ -272,7 +275,7 @@ function build_other_arch() {
 	local PKGNAME="$1" SOURCETARBALL="$2" ARCH="$3"
 	
 	# First, pass the source tarball into the VM
-	sshpass -p $SSHPASSWORD scp -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -P $SSHPORT "$SOURCETARBALL" $SSHUSER@127.0.0.1:/tmp/$(basename $SOURCETARBALL) >/dev/null 2>&1
+	sshpass -p $SSHPASSWORD scp -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -P $SSHPORT "$SOURCETARBALL" "$SSHUSER@127.0.0.1:/tmp/$(basename "$SOURCETARBALL")" >/dev/null 2>&1
 	
 	# The following commands (After sshpass / ssh, until 'EOF') are passed directly to the VM
 	# Here we connect and build the packages
@@ -294,9 +297,9 @@ mkdir "$PKGNAME"
 
 cd "$PKGNAME"
 
-mv /tmp/$(basename $SOURCETARBALL) .
-tar -xzf ./$(basename $SOURCETARBALL)
-rm ./$(basename $SOURCETARBALL)
+mv /tmp/$(basename "$SOURCETARBALL") .
+tar -xzf ./$(basename "$SOURCETARBALL")
+rm ./$(basename "$SOURCETARBALL")
 
 debuild -us -uc
 
@@ -318,7 +321,7 @@ EOF
 
 	sshpass -p $SSHPASSWORD scp -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -P $SSHPORT -r $SSHUSER@127.0.0.1:/home/debian/build/pkg/packages.tar.gz "$initdir/$ARCH/packages.tar.gz" >/dev/null 2>&1
 	
-	cd "$initdir/$ARCH"
+	cd "$initdir/$ARCH" || { echo "Could not cd into \"$initdir/$ARCH\""; exit 1; }
 	tar -xzf packages.tar.gz
 	rm -f packages.tar.gz
 	mv "$initdir/$ARCH/"*.deb "$initdir/buildfarm-debs/"
@@ -398,7 +401,7 @@ function push_github_release_page() {
 	# Create GitHub Release
 	
 	## Make sure we're in the package's release directory
-	cd $basereleasedir/$PKGNAME
+	cd "$basereleasedir/$PKGNAME" || { echo "Could not cd into \"$basereleasedir/$PKGNAME\""; exit 1; }
 	
 	## Send POST request to GitHub API to create a release page
 	curl -L \
@@ -423,7 +426,7 @@ function push_github_release_page() {
 	
 	## Get the list of package files
 	for file in $(ls); do
-		list_of_pkg_files+=("$(echo $file | grep -P -e $PKGNAME.*.deb)")
+		list_of_pkg_files+=("$(echo "$file" | grep -P -e $PKGNAME.*.deb)")
 	done
 	
 	## Upload the attachments via POST request to the GitHub API
@@ -440,20 +443,20 @@ function push_github_release_page() {
 		fi
 	done
 	
-	cd $initdir
+	cd "$initdir"
 }
 
 function prepare_ghpages_debian_repo() {
 	# Clone the git repo into a local directory
-	cd "$storagedir"
+	cd "$storagedir" || { echo "Could not cd into \"$storagedir\""; exit 1; }
 	git clone "$git_debianrepo" "$local_repodirectory" -q 2>/dev/null
-	cd "$local_repodirectory"
+	cd "$local_repodirectory" || { echo "Could not cd into \"$local_repodirectory\""; exit 1; }
 	git reset --hard
 	git pull -q
 }
 
 function close_ghpages_debian_repo() {
-	cd "$storagedir/$local_repodirectory"
+	cd "$storagedir/$local_repodirectory" || { echo "Could not cd into \"$storagedir/$local_repodirectory\""; exit 1; }
 	
 	# Push the changes we've made before calling this function
 	git push origin -q
@@ -473,8 +476,8 @@ function push_to_ghpages_debian_repo() {
 	
 	local PKGNAME="$1" CHANGESFILE="" list_of_pkg_files=()
 	
-	cd "$storagedir/$local_repodirectory"
-	cd debian
+	cd "$storagedir/$local_repodirectory" || { echo "Could not cd into \"$storagedir/$local_repodirectory\""; exit 1; }
+	cd debian || { echo "$PKGNAME does not appear to contain a 'debian' subdirectory"; exit 1; }
 	
 	
 	# Get the .changes file
@@ -486,7 +489,7 @@ function push_to_ghpages_debian_repo() {
 	
 	# Get the list of all .deb package files that are NOT marked with $host_architecture (default: amd64)
 	for file in $(ls "$basereleasedir/$PKGNAME/"); do
-		list_of_pkg_files+=("$(echo $file | grep -P -e $PKGNAME.*.deb | grep -v "$host_architecture")")
+		list_of_pkg_files+=("$(echo "$file" | grep -P -e $PKGNAME.*.deb | grep -v "$host_architecture")")
 	done
 	
 	# Add those to the repo with includedeb
@@ -497,7 +500,7 @@ function push_to_ghpages_debian_repo() {
 	done
 	
 	# Update indexes and commit changes
-	cd "$storagedir/$local_repodirectory"
+	cd "$storagedir/$local_repodirectory" || { echo "Could not cd into \"$storagedir/$local_repodirectory\""; exit 1; }
 	./update-indexes.sh
 	git add --all
 	git commit -m "Updated $PKGNAME"
@@ -512,7 +515,7 @@ function ask_user_build_pkg() {
 	local PKGNAME="$1"
 	
 	while true; do
-		read -p "Do you want to build $PKGNAME? (y/N) " yn
+		read -r -p "Do you want to build $PKGNAME? (y/N) " yn
 		case $yn in
 			[Yy]* ) buildbasepkgs+=("$PKGNAME"); break;;
 			* ) return 1;;
@@ -520,7 +523,7 @@ function ask_user_build_pkg() {
 	done
 	
 	while true; do
-		read -p "  $PKGNAME: Build on i386 as well? (y/N) " yn
+		read -r -p "  $PKGNAME: Build on i386 as well? (y/N) " yn
 		case $yn in
 			[Yy]* ) buildi386pkgs+=("$PKGNAME"); break;;
 			* ) break;;
@@ -528,7 +531,7 @@ function ask_user_build_pkg() {
 	done
 	
 	while true; do
-		read -p "  $PKGNAME: Build on arm64 as well? (y/N) " yn
+		read -r -p "  $PKGNAME: Build on arm64 as well? (y/N) " yn
 		case $yn in
 			[Yy]* ) buildarm64pkgs+=("$PKGNAME"); break;;
 			* ) break;;
@@ -539,7 +542,7 @@ function ask_user_build_pkg() {
 function ask_user_publish_to_deb_repo() {
 	for pkgname in "${buildbasepkgs[@]}"; do
 		while true; do
-			read -p "Do you want to publish $pkgname to your Git-based Debian Repository? (y/n) " yn
+			read -r -p "Do you want to publish $pkgname to your Git-based Debian Repository? (y/n) " yn
 			case $yn in
 				[Yy]* ) pkgstopublish+=("$pkgname"); break;;
 				[Nn]* ) break;;
@@ -566,7 +569,7 @@ function maybe_publish_to_deb_repo() {
 function ask_user_make_github_release_page() {	
 	for pkgname in "${buildbasepkgs[@]}"; do
 		while true; do
-			read -p "Do you want to make a GITHUB RELEASE PAGE for $pkgname? (y/n) " yn
+			read -r -p "Do you want to make a GITHUB RELEASE PAGE for $pkgname? (y/n) " yn
 			case $yn in
 				[Yy]* ) releasepagestomake+=("$pkgname"); break;;
 				[Nn]* ) break;;
@@ -688,7 +691,7 @@ while true; do
 		-h | --help )
 			display_help; exit 0; shift ;;
 		-o | --output )
-			savedir="$(realpath $2)"; shift 2 ;;
+			savedir="$(realpath "$2")"; shift 2 ;;
 		-p | --package )
 			if [ ${packages[$2]+1} ]; then
 				buildbasepkgs+=("$2");
@@ -747,7 +750,7 @@ fi
 build_all_pkgs_in_pkgarrays
 clean_up
 
-if [ interactive_mode == true ]; then
+if [ $interactive_mode == true ]; then
 	ask_user_publish_to_deb_repo
 	ask_user_make_github_release_page
 fi
