Make sure a package was provided

diff --git a/autobuild b/autobuild
--- a/autobuild
+++ b/autobuild
@@ -591,6 +591,7 @@ if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 
 eval set -- "$TEMP"
 
+package_provided=false
 target_architecture_provided=false
 building_on_amd64=false
 building_on_i386=false
@@ -641,6 +642,7 @@ while true; do
 		-p | --package )
 			if [ ${packages[$2]+1} ]; then
 				packages_to_build+=("$2");
+				package_provided=true
 				echo "Building $2"
 			else
 				echo "ERROR: Package '$2' not in CONFIG!";
@@ -655,6 +657,12 @@ while true; do
 done
 
 setup_build_environment
+
+if [ $package_provided == false ]; then
+	echo "Error: No package names provided."
+	echo "See 'autobuild -h' or 'man autobuild' for more information."
+	exit 1
+fi
 
 if [ $target_architecture_provided == false ]; then
 	echo "Error: No target architecture provided. Assuming amd64..."
